### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stan1rex**
hackip run --details --chat --cuttly_api_key YOUR_CUTTLY_API_KEY --openai_key YOUR_OPENAI_API_KEY

### CODE REVIEW

**Comment by subhomoy-roy-choudhury** [comment]
@stan1rex please do some meaningful contributions. If you need any help in understanding the project please let me know

**Comment by subhomoy-roy-choudhury** [comment]
Yes I will. Will be sharing my calendly link. Please schedule a call as per your convenience

**Comment by stan1rex** [comment]
I didn’t understand can you do it for me please
Here is the ip 185.147.101.18

**Comment by subhomoy-roy-choudhury** [comment]
Please schedule a call using this link https://calendly.com/subhomoyrchoudhury/30min.

**Pull request merged**
